name: Django CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 1
        persist-credentials: false
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create Static Directory
      run: |
        mkdir -p static
        mkdir -p staticfiles
        
    - name: Prepare Static Files
      run: |
        cp chat/templates/home.html staticfiles/index.html
        if [ -d "static" ]; then cp -r static/* staticfiles/ || true; fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./staticfiles
        enable_jekyll: false
        force_orphan: true 